classDiagram
  class PaymentCardBrand {
    <<enumeration>>
    amex
    mastercard
    visa
    other
  }
  class EncoderProtocol {
    <<interface>>
    +decode(bytes data) bytes$
    +encode(bytes value) bytes$
    +get_json_format() str$
  }
  class Base64Encoder {
    +decode(bytes data) bytes$
    +encode(bytes value) bytes$
    +get_json_format() Literal~base64~$
  }
  class EncodedBytes {
    +type~EncoderProtocol~ encoder
    +decode(bytes data, core_schema.ValidationInfo _) bytes
    +encode(bytes value) bytes
  }
  class PaymentCardNumber {
    +bool strip_whitespace$
    +int min_length$
    +int max_length$
    +str bin
    +str last4
    +PaymentCardBrand brand
    +str masked
    -__init__(str card_number)
    +validate(core_schema.ValidationInfo _) PaymentCardNumber$
    +validate_digits(str card_number) None$
    +validate_luhn_check_digit(str card_number) str$
    +validate_brand(str card_number) PaymentCardBrand$
  }
  EncoderProtocol <|-- Base64Encoder
