PaymentCardBrand: {
  shape: class
  amex
  mastercard
  visa
  other
}
EncoderProtocol: {
  shape: class
  +decode(data: bytes): bytes
  +encode(value: bytes): bytes
  +get_json_format(): str
}
Base64Encoder: {
  shape: class
  +decode(data: bytes): bytes
  +encode(value: bytes): bytes
  +get_json_format(): Literal<base64>
}
EncodedBytes: {
  shape: class
  +encoder: type<EncoderProtocol>
  +decode(data: bytes, _: core_schema.ValidationInfo): bytes
  +encode(value: bytes): bytes
}
PaymentCardNumber: {
  shape: class
  +strip_whitespace: bool
  +min_length: int
  +max_length: int
  +bin: str
  +last4: str
  +brand: PaymentCardBrand
  +masked: str
  -__init__(card_number: str)
  +validate(_: core_schema.ValidationInfo): PaymentCardNumber
  +validate_digits(card_number: str): None
  +validate_luhn_check_digit(card_number: str): str
  +validate_brand(card_number: str): PaymentCardBrand
}
Base64Encoder -> EncoderProtocol: extends
