@startuml
package pydantic.types {
  enum PaymentCardBrand {
    amex
    mastercard
    visa
    other
  }
  interface EncoderProtocol {
    + {static} decode(data: bytes) : bytes
    + {static} encode(value: bytes) : bytes
    + {static} get_json_format() : str
  }
  class Base64Encoder {
    + {static} decode(data: bytes) : bytes
    + {static} encode(value: bytes) : bytes
    + {static} get_json_format() : Literal<base64>
  }
  class EncodedBytes {
    + encoder : type<EncoderProtocol>
    + decode(data: bytes, _: core_schema.ValidationInfo) : bytes
    + encode(value: bytes) : bytes
  }
  class PaymentCardNumber {
    + {static} strip_whitespace : bool = True
    + {static} min_length : int = 12
    + {static} max_length : int = 19
    + bin : str
    + last4 : str
    + brand : PaymentCardBrand
    + masked : str
    - __init__(card_number: str)
    + {static} validate(_: core_schema.ValidationInfo) : PaymentCardNumber
    + {static} validate_digits(card_number: str) : None
    + {static} validate_luhn_check_digit(card_number: str) : str
    + {static} validate_brand(card_number: str) : PaymentCardBrand
  }
}
EncoderProtocol <|-- Base64Encoder
@enduml
